### ISSUE TITLE
路由跳转标题不显示

### ISSUE THREAD

**Issue by PineSong96** [luichooy/vue-admin#1]
router/index.js
  setTitle(to.meta.title);
你的路由的title并没有放进meta，但是你这样写了所以标题没有生效

**Comment by luichooy** [comment]
> router/index.js
> setTitle(to.meta.title);
> 你的路由的title并没有放进meta，但是你这样写了所以标题没有生效

是的，感谢指正。不过项目中也可以根据情况灵活使用
