### ISSUE TITLE
权限设置问题

### ISSUE THREAD

**Issue by wqs2019** [luichooy/vue-admin#3]
您好，我想问一下关于左边的菜单，如何做权限设置？比如管理员可以看到权限设置，普通的就不可以。
配置是这样的
{
          path: '/access/index',
          title: '权限管理',
          icon: 'el-icon-adm-organization',
          onlyAdmin: true //管理员可见
        },
这里循环应该怎么写呢？

<template v-for="(item, index) in sider_menu_data">
          <el-menu-item class="menu-item" v-if="!item.children" :index="item.path" :key="index">
            <i :class="item.icon"></i>
            <span slot="title">{{item.title}}</span>
          </el-menu-item>

          <el-submenu v-else :index="item.path" :key="index">
            <template slot="title">
              <i :class="item.icon"></i>
              <span slot="title">{{item.title}}</span>
            </template>
            <el-menu-item
              class="menu-item"
              v-for="(sub_item, sub_index) in item.children"
              :index="sub_item.path"
              :key="sub_index"
            >
              <span slot="title" style="margin-left:12px;">{{sub_item.title}}</span>
            </el-menu-item>
          </el-submenu>
        </template>

**Comment by luichooy** [comment]
> <el-submenu v-else :index="item.path" :key="index">
>         <template slot="title">
>           <i :class="item.icon"></i>
>           <span slot="title">{{item.title}}</span>
>         </template>
>         <el-menu-item
>           class="menu-item"
>           v-for="(sub_item, sub_index) in item.children"
>           :index="sub_item.path"
>           :key="sub_index"
>         >
>           <span slot="title" style="margin-left:12px;">{{sub_item.title}}</span>
>         </el-menu-item>
>       </el-submenu>

```
<el-submenu v-else :index="item.path" :key="index">
  <template slot="title">
    <i :class="item.icon"></i>
    <span slot="title">{{item.title}}</span>
  </template>
  
  <template v-for="(sub_item, sub_index) in item.children">
    <el-menu-item
      v-if="sub_item.onlyAdmin"
      :key="sub_index"
      :index="sub_item.path"
      class="menu-item"
    >
      <span slot="title" style="margin-left:12px;">{{sub_item.title}}</span>
    </el-menu-item>
  </template>
</el-submenu>
```

**Comment by luichooy** [comment]
> 

>

**Comment by luichooy** [comment]
> 您好，我想问一下关于左边的菜单，如何做权限设置？比如管理员可以看到权限设置，普通的就不可以。
> 配置是这样的
> {
> path: '/access/index',
> title: '权限管理',
> icon: 'el-icon-adm-organization',
> onlyAdmin: true //管理员可见
> },
> 这里循环应该怎么写呢？
> 
> {{item.title}}
> ```
>       <el-submenu v-else :index="item.path" :key="index">
>         <template slot="title">
>           <i :class="item.icon"></i>
>           <span slot="title">{{item.title}}</span>
>         </template>
>         <el-menu-item
>           class="menu-item"
>           v-for="(sub_item, sub_index) in item.children"
>           :index="sub_item.path"
>           :key="sub_index"
>         >
>           <span slot="title" style="margin-left:12px;">{{sub_item.title}}</span>
>         </el-menu-item>
>       </el-submenu>
>     </template>
> ```

在 for 循环内部加 if 判断即可
```
<el-submenu v-else :index="item.path" :key="index">
  <template slot="title">
    <i :class="item.icon"></i>
    <span slot="title">{{item.title}}</span>
  </template>
  
  <template v-for="(sub_item, sub_index) in item.children">
    <el-menu-item
      v-if="sub_item.onlyAdmin"
      :key="sub_index"
      :index="sub_item.path"
      class="menu-item"
    >
      <span slot="title" style="margin-left:12px;">{{sub_item.title}}</span>
    </el-menu-item>
  </template>
</el-submenu>
```
